name: Google Space Notification
description: Test Google Space Notification
inputs:
  title:
    description: The title of this release
    required: true
  webhook-url:
    description: The Google Space Webhook
    required: true
  version:
    description: The version of the release
    required: true
  release-notes:
    description: Release Notes
    required: false
    default: ""
  release-html-url:
    description: A link to the release page
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Goggle Space Notification
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1
