name: Google Space Notification
description: Build or Test a container image and apply labels
inputs:
  title:
    description: The title of this release
    required: true
  webhook:
    description: The Google Space Webhook
    required: true
  version:
    description: The version of the release
    required: true
  release-notes:
    description: Release Notes
    required: false
    default: ""
  release-html-url:
    description: A link to the release page
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Goggle Space Notification
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1 -Title '${{ inputs.title }}' -Webhook '${{ inputs.webhook }}' -Version '${{ inputs.version }}' -ReleaseNotes '${{ inputs.release-notes }}' -ReleaseHtmlUrl '${{ inputs.release-html-url }}'
